### ISSUE TITLE
Change DroidiconBadge background programmatically

### ISSUE THREAD

**Issue by ivanma72** [theDazzler/droidicon#19]
I have a button in my code like this. Note that I have the circular background be transparent:

                    <com.thedazzler.droidicon.badges.DroidiconBadge
                        android:id="@+id/nav_calibration_badge"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        droidicon:db_bg_color="@android:color/transparent"
                        droidicon:db_icon_color="#f44336"
                        droidicon:db_icon="fa-compass"
                        droidicon:db_size="36dp"
                        droidicon:db_icon_padding="8dp"/>

I'm trying to find a way to change the background color in code, but I'm not how to do so. Using DroidiconBadge.setBackground(...) changes the background to a square.

**Comment by theDazzler** [comment]
@ivanma72 I just added it. You can now do DroidiconBadge.setBackgroundColor(). Also added setContourColor() and setIconColor()
