### ISSUE TITLE
work with drawables & add invert-method/inverted-style

### ISSUE THREAD

**Issue by ShawnOceanHu** [theDazzler/droidicon#21]
Hi, awesome work :)
Wondering can this work with drawables ? like:
```
background="@drawable/fa-home"
```
And add customized attrs like 'inverted' to drawable ?

Just like the CSS counterparts.

**Comment by theDazzler** [comment]
@ShawnOceanHu What are you trying to do? Why do you want to do it that way?

**Comment by ShawnOceanHu** [comment]
Actually I myself am not so sure right now, been busy on another html5 project, sorry guys : )

I'll close this issue now.

**Comment by philippeluickx** [comment]
+1 on this request.
I prefer to add an icon to e.g. FloatingActionButton through the xml, instead of having to code my way around it in the Activity or Fragment.
