### ISSUE TITLE
Creating a icon circular background programatically.

### ISSUE THREAD

**Issue by theaidorus** [theDazzler/droidicon#24]
Hi,

I am wondering how can i create a icon with circular background?

what am i trying to do:

IconicFontDrawable iconicFontDrawable = new IconicFontDrawable(this.getApplicationContext());
iconicFontDrawable.setIcon("fa-thumbs-up");
iconicFontDrawable.setIconColor(getResources().getColor(R.color.light_blue));

//setBackground will fulfill the whole view with icon

i saw issue #19  however setBackgroundColor is not present anymore.

Can somebody help me? 

Thanks

**Comment by theDazzler** [comment]
@theaidorus You can easily do this with a DroidiconBadge
```

DroidiconBadge customBadge = (DroidiconBadge) findViewById(R.id.customBadge);
customBadge.setBackgroundColor(getResources().getColor(R.color.light_blue));
customBadge.setIcon("fa-thumbs-up");

```
Then in your xml, add this view. You can change the color of the icon too
```
<com.thedazzler.droidicon.badges.DroidiconBadge
                    android:id="@+id/customBadge"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    droidicon:db_icon_color="@color/white"
                    />
```

**Comment by theaidorus** [comment]
Thanks for the reply. Now my question is that, can I make a drawable with an icon and circular background?

Thank you

**Comment by theDazzler** [comment]
@theaidorus What are you actually trying to do anyways? There is probably an easier way. 

There are ways to do it. One way is to make your own custom drawable with a circular background. Another way is to create your own font. Droidicon supports custom fonts. There is an example here https://github.com/theDazzler/droidicon/blob/master/droidicon_test/src/main/java/com/thedazzler/droidicon/test/MainActivity.java starting at line 94. 

Look at the icon "fa-question-circle". It's a drawable with a circular background.

**Comment by theaidorus** [comment]
What I am trying to do is:
I am using another library for floating action button, and to set the icon,  i need to replace it with a drawable. Now, I want to use your library, to replace the button. That is why I need to create a drawable with circular background. Thanks

**Comment by theDazzler** [comment]
@theaidorus Most of those libraries allow you to change the background color of the button within the library. Then you would just add an IconicFontDrawable to it. Also, if you use a DroidiconBadge, there is this method: getIconicFontDrawable() which returns the icon as a Drawable. What floating action button library are you using? There are a bunch of them

**Comment by theaidorus** [comment]
I use that exact library (https://github.com/futuresimple/android-floating-action-button). If you look at futuresimple's sample, the library extends button. It has, setIcon() and setBackground. Yet, the actual library has been changed to extend imageView. Now, there is no setIcon, just setBackground and setBackgroundDrawable. That is why I opt to use your library.

**Comment by theaidorus** [comment]
Do you have a solution for me? 

Thanks

**Comment by theDazzler** [comment]
@theaidorus I looked at that library's code and there are methods setIcon(), setIconDrawable(), setColorNormal(). Also, an ImageButton's background color can be changed with
```
android:background="#rrggbb" 
```
You should be able to just set background color through xml and then use setIcon() or setIconDrawable(). Have you tried that? Also, try asking this question in that library's issues. You just need to know how to set the background color of the FloatingActionButton, and I'm assuming you can do it with one of the ways I provided.
