### ISSUE TITLE
Attribute "rippleColor" has already been defined

### ISSUE THREAD

**Issue by tausiq** [theDazzler/droidicon#25]
compile 'com.android.support:design:23.0.0'

after adding the above library, Gradle build failed with error, 

```
/SOURCE_CODE_PATH/build/intermediates/exploded-aar/com.github.theDazzler/droidicon/0.1.3/res/values/values.xml
Error:(2) Attribute "rippleColor" has already been defined
Error:Execution failed for task ':core:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/shahabuddin/Library/Android/sdk/build-tools/23.0.0/aapt'' finished with non-zero exit value 1
```

Removing the support design library resolves the problem.

**Comment by theDazzler** [comment]
@tausiq I think that error has to do with different support library versions. You can read this stackoverflow thread for possible solutions: http://stackoverflow.com/questions/19995970/error-attribute-has-already-been-defined-when-using-two-library-projects
