### ISSUE TITLE
adding icons to buttons and menues

### ISSUE THREAD

**Issue by Fshamri** [theDazzler/droidicon#26]
I want to replace the i cons i use in navigation view with droidicon where i use menu layout.
this is my current layout:

      <menu xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_gravity="end">
    <group android:id="@+id/menu_group_1"
        android:checkableBehavior="single">
        <item
            android:id="@+id/menu_latest_news"
            android:checked="true"
            android:icon="@drawable/ic_earth_grey600_24dp"
            android:title="@string/menu.drawer.stories.latest" />
        <item
            android:id="@+id/drawar_menu_saved_stories"
            android:icon="@drawable/ic_download_grey600_24dp"
            android:title="@string/menu.drawer.stories.saved" />
        <item
            android:id="@+id/drawar_menu_sources"
            android:icon="@drawable/analytics_gray"
            android:title="@string/menu.drawer.stories.resources" />
        <item

My question is how can i add droidicon to my layout. Also how can i add icons programaticaly?

**Comment by theDazzler** [comment]
@Fshamri adding icons programmatically is explained in the wiki here https://github.com/theDazzler/droidicon/wiki/How-to-Use under "Custom Icons". From there, it is easy to add the icons to your navigation. One way is to use an Adapter and do something like 
```
adapter.addItem(new MenuItem("Search", searchDrawable));
```
