### ISSUE TITLE
Instagram icon appears very small

### ISSUE THREAD

**Issue by Spainman2015** [theDazzler/droidicon#27]
Hi there, 
I use droidicon for my app and it works great. Now I need the instagram icon and I have followed the same steps as usual, just like the facebook icon. The logo of instagram appears like 1 pixel in size compared to facebook, but the code is the same. See below and see attached screenshot. 

Can anyone help me? Thanks. 

[See Image](http://s28.postimg.org/o5jwatulp/Instagram.png)

   <com.thedazzler.droidicon.badges.FacebookDroidiconBadge
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginRight="10dp"
                        android:layout_marginEnd="10dp"
                        app:db_size="40dp"
                        android:id="@+id/am_iv_facebook" />

                    <com.thedazzler.droidicon.badges.InstagramDroidiconBadge
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginRight="10dp"
                        android:layout_marginEnd="10dp"
                        app:db_size="40dp"
                        android:id="@+id/am_iv_instagram" />

**Comment by theDazzler** [comment]
@Spainman2015 I'm not sure what is causing this. I tried your code and everything worked fine. What does your parent layout code look like?
